@include('site.includes.header');

    <!-- header 1 -->
    <div class="header1 blog-post">
        <div class="container">
            <div class="row">
                <div class="col-sm-8">
                    <div class="text-container text-left">
                        <a href="index.html">Home / </a>
                        <a href="blog-post.html#"> Blog Post</a>
                        <h2>{{$serviceContent[0]->servicename}}</h2>
                    <p>{{$serviceContent[0]->subcategory}}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- header 1 end -->

    <!-- blog section -->
    <div class="blog">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="post-container">
                        <div class="blog-img">
                        </div>
                        <!--div class="post-title">
                            <h2>Just a dummy text</h2>
                            <div class="blog-date">
                                <p>Monday / Aug 2019</p>
                            </div>
                        </div-->
                        <div class="post-text">
                            <h1 style="box-sizing: border-box; margin: 0px 0px 0.5rem; font-size: 33px; font-family: Muli, sans-serif; font-weight: bold; line-height: 1.2; color: rgb(255, 113, 22); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; padding: 35px 0px 16px; border-bottom: 1px solid rgb(238, 238, 238); letter-spacing: 1px; text-align: left; background-color: rgb(255, 255, 255);"><strong><em><span style="color: rgb(85, 57, 130); font-size: 18px;">Private Limited Company (For Resident Indian)</span></em></strong></h1>
                            <div style='box-sizing: border-box; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; display: flex; flex-flow: column wrap; align-items: center; width: 798px; max-width: 798px; color: rgb(38, 38, 38); font-family: "Open Sans", sans-serif; font-size: 16px; letter-spacing: 1px; text-align: left; background-color: rgb(255, 255, 255);'>
                                <div style="box-sizing: border-box; width: 798px; position: relative; margin-bottom: 25px; line-height: 25px; font-size: 1em; text-align: left; padding: 0px 15px; min-height: 375px; overflow: hidden; height: 1059px;">
                                    <div style="box-sizing: border-box; margin-bottom: 0.0001pt; text-align: left; line-height: normal; background: white;"><span style='color: blue; font-size: 14px; font-family: "Times New Roman", Times, serif, -webkit-standard;'>All you need to know about establishing a Private Limited Company</span></div>
                                    <div style="box-sizing: border-box; margin-bottom: 0.0001pt; text-align: left; line-height: normal; background: white;"><span style="font-family: Times New Roman,Times,serif,-webkit-standard;"><span style="color: blue;"><span style="font-size: 14px;">&nbsp;</span></span></span></div>
                                    <div style="box-sizing: border-box; margin-bottom: 0.0001pt; text-align: left; line-height: normal; background: white;"><span style="font-family: Times New Roman,Times,serif,-webkit-standard;"><span style="color: blue;"><span style="font-size: 14px;">Taking the road less taken can turn out to be one of the most fulfilling&nbsp;</span></span></span><span style='font-size: 14px; color: blue; font-family: "Times New Roman", Times, serif, -webkit-standard;'>experiences of a lifetime.</span></div>
                                    <div style="box-sizing: border-box; margin-bottom: 0.0001pt; text-align: left; line-height: normal; background: white;"><span style='font-size: 14px; color: blue; font-family: "Times New Roman", Times, serif, -webkit-standard;'>&nbsp;There is hardly any joy in doing the things&nbsp;</span><span style='font-size: 14px; color: blue; font-family: "Times New Roman", Times, serif, -webkit-standard;'>everyone can do.&nbsp;</span></div>
                                    <div style="box-sizing: border-box; margin-bottom: 0.0001pt; text-align: left; line-height: normal; background: white;"><span style='font-size: 14px; color: blue; font-family: "Times New Roman", Times, serif, -webkit-standard;'>But there is a joy mighty sweet when you succeed on a&nbsp;</span></div>
                                    <div style="box-sizing: border-box; margin-bottom: 0.0001pt; text-align: left; line-height: normal; background: white;"><span style="font-family: Times New Roman,Times,serif,-webkit-standard;"><span style="color: blue;"><span style="font-size: 14px;">road less taken and become an inspiration for generations to come.</span></span></span></div>
                                    <div style="box-sizing: border-box; margin-bottom: 0.0001pt; text-align: left; line-height: normal; background: white;"><span style="font-family: Times New Roman,Times,serif,-webkit-standard;"><span style="color: blue;"><span style="font-size: 14px;">&nbsp;</span></span></span></div>
                                    <div style="box-sizing: border-box; margin-bottom: 0.0001pt; text-align: left; line-height: normal; background: white;"><span style="font-family: Times New Roman,Times,serif,-webkit-standard;"><span style="color: blue;"><span style="font-size: 14px;">Starting a business can turn out to be one of the most interesting experiences</span></span></span></div>
                                    <div style="box-sizing: border-box; margin-bottom: 0.0001pt; text-align: left; line-height: normal; background: white;"><span style="font-family: Times New Roman,Times,serif,-webkit-standard;"><span style="color: blue;"><span style="font-size: 14px;">&nbsp;of your life. One of the important decisions made by an entrepreneur or a</span></span></span></div>
                                    <div style="box-sizing: border-box; margin-bottom: 0.0001pt; text-align: left; line-height: normal; background: white;"><span style="font-family: Times New Roman,Times,serif,-webkit-standard;"><span style="color: blue;"><span style="font-size: 14px;">&nbsp;start-up while starting this journey is the selection of his business entity.&nbsp;</span></span></span></div>
                                    <div style="box-sizing: border-box; margin-bottom: 0.0001pt; text-align: left; line-height: normal; background: white;"><span style="font-family: Times New Roman,Times,serif,-webkit-standard;"><span style="color: blue;"><span style="font-size: 14px;">The choice of the business entity has long term implications throughout the&nbsp;</span></span></span></div>
                                    <div style="box-sizing: border-box; margin-bottom: 0.0001pt; text-align: left; line-height: normal; background: white;"><span style="font-family: Times New Roman,Times,serif,-webkit-standard;"><span style="color: blue;"><span style="font-size: 14px;">life-cycle of the business. Hence, it is recommended to discuss your business</span></span></span></div>
                                    <div style="box-sizing: border-box; margin-bottom: 0.0001pt; text-align: left; line-height: normal; background: white;"><span style="font-family: Times New Roman,Times,serif,-webkit-standard;"><span style="color: blue;"><span style="font-size: 14px;">&nbsp;plan with a professional, and choose an entity that will support the vision of&nbsp;</span></span></span></div>
                                    <div style="box-sizing: border-box; margin-bottom: 0.0001pt; text-align: left; line-height: normal; background: white;"><span style="font-family: Times New Roman,Times,serif,-webkit-standard;"><span style="color: blue;"><span style="font-size: 14px;">the business.</span></span></span></div>
                                    <div style="box-sizing: border-box; margin-bottom: 0.0001pt; text-align: left; line-height: normal; background: white;"><span style="font-family: Times New Roman,Times,serif,-webkit-standard;"><span style="color: blue;"><span style="font-size: 14px;">&nbsp;</span></span></span></div>
                                    <div style="box-sizing: border-box; margin-bottom: 0.0001pt; text-align: left; line-height: normal; background: white;"><span style="font-family: Times New Roman,Times,serif,-webkit-standard;"><span style="color: blue;"><span style="font-size: 14px;">Cut to the chase; we highly recommend you opt for setting up a&nbsp;</span></span></span></div>
                                    <div style="box-sizing: border-box; margin-bottom: 0.0001pt; text-align: left; line-height: normal; background: white;"><span style="font-family: Times New Roman,Times,serif,-webkit-standard;"><span style="color: blue;"><span style="font-size: 14px;">Private Limited Company. Read on and you&rsquo;ll understand why.</span></span></span></div>
                                    <div style="box-sizing: border-box; margin-bottom: 0.0001pt; text-align: left; line-height: normal; background: white;"><span style="font-family: Times New Roman,Times,serif,-webkit-standard;"><span style="color: blue;"><span style="font-size: 14px;">&nbsp;</span></span></span></div>
                                    <div style="box-sizing: border-box; margin-bottom: 0.0001pt; text-align: left; line-height: normal; background: white;"><span style="font-family: Times New Roman,Times,serif,-webkit-standard;"><span style="color: blue;"><span style="font-size: 14px;">A Private Limited Company is the most popular as well as the most preferred&nbsp;</span></span></span></div>
                                    <div style="box-sizing: border-box; margin-bottom: 0.0001pt; text-align: left; line-height: normal; background: white;"><span style="font-family: Times New Roman,Times,serif,-webkit-standard;"><span style="color: blue;"><span style="font-size: 14px;">choice of business entity in India. As it requires a minimum of 2 members, it is&nbsp;</span></span></span></div>
                                    <div style="box-sizing: border-box; margin-bottom: 0.0001pt; text-align: left; line-height: normal; background: white;"><span style="font-family: Times New Roman,Times,serif,-webkit-standard;"><span style="color: blue;"><span style="font-size: 14px;">most appropriate for small and medium-sized businesses and start-ups. It is a&nbsp;</span></span></span></div>
                                    <div style="box-sizing: border-box; margin-bottom: 0.0001pt; text-align: left; line-height: normal; background: white;"><span style="font-family: Times New Roman,Times,serif,-webkit-standard;"><span style="color: blue;"><span style="font-size: 14px;">privately held business entity with a limited liability and allows for a 100%&nbsp;</span></span></span></div>
                                    <div style="box-sizing: border-box; margin-bottom: 0.0001pt; text-align: left; line-height: normal; background: white;"><span style="font-family: Times New Roman,Times,serif,-webkit-standard;"><span style="color: blue;"><span style="font-size: 14px;">foreign direct investment with government approval. It takes only around two</span></span></span></div>
                                    <div style="box-sizing: border-box; margin-bottom: 0.0001pt; text-align: left; line-height: normal; background: white;"><span style="font-family: Times New Roman,Times,serif,-webkit-standard;"><span style="color: blue;"><span style="font-size: 14px;">&nbsp;weeks to set up a Private Limited Company. It also allows a significant degree&nbsp;</span></span></span></div>
                                    <div style="box-sizing: border-box; margin-bottom: 0.0001pt; text-align: left; line-height: normal; background: white;"><span style="font-family: Times New Roman,Times,serif,-webkit-standard;"><span style="color: blue;"><span style="font-size: 14px;">of distinction between the business entity and the management.</span></span></span></div>
                                    <div style="box-sizing: border-box; margin-bottom: 0.0001pt; text-align: left; line-height: normal; background: white;"><span style="font-family: Times New Roman,Times,serif,-webkit-standard;"><span style="color: blue;"><span style="font-size: 14px;">&nbsp;</span></span></span></div>
                                    <div style="box-sizing: border-box; margin-bottom: 0.0001pt; text-align: left; line-height: normal; background: white;"><span style="font-family: Times New Roman,Times,serif,-webkit-standard;"><span style="color: blue;"><span style="font-size: 14px;">Basic requirements for Private Limited Company Registration:</span></span></span></div>
                                    <div style="box-sizing: border-box; margin-bottom: 0.0001pt; text-align: left; line-height: normal; background: white;"><span style="font-family: Times New Roman,Times,serif,-webkit-standard;"><span style="color: blue;"><span style="font-size: 14px;">&nbsp;</span></span></span></div>
                                    <div style="box-sizing: border-box; margin-bottom: 0.0001pt; text-align: left; line-height: normal; background: white;"><span style="font-family: Times New Roman,Times,serif,-webkit-standard;"><span style="color: blue;"><span style="font-size: 14px;">1. A minimum 2 Shareholders are required</span></span></span></div>
                                    <div style="box-sizing: border-box; margin-bottom: 0.0001pt; text-align: left; line-height: normal; background: white;"><span style="font-family: Times New Roman,Times,serif,-webkit-standard;"><span style="color: blue;"><span style="font-size: 14px;">&nbsp;</span></span></span></div>
                                    <div style="box-sizing: border-box; margin-bottom: 0.0001pt; text-align: left; line-height: normal; background: white;"><span style="font-family: Times New Roman,Times,serif,-webkit-standard;"><span style="color: blue;"><span style="font-size: 14px;">2. A minimum 2 Directors are required</span></span></span></div>
                                    <div style="box-sizing: border-box; margin-bottom: 0.0001pt; text-align: left; line-height: normal; background: white;"><span style="font-family: Times New Roman,Times,serif,-webkit-standard;"><span style="color: blue;"><span style="font-size: 14px;">&nbsp;</span></span></span></div>
                                    <div style="box-sizing: border-box; margin-bottom: 0.0001pt; text-align: left; line-height: normal; background: white;"><span style="font-family: Times New Roman,Times,serif,-webkit-standard;"><span style="color: blue;"><span style="font-size: 14px;">3. The Directors and Shareholders generally be the same person</span></span></span></div>
                                    <div style="box-sizing: border-box; margin-bottom: 0.0001pt; text-align: left; line-height: normal; background: white;"><span style="font-family: Times New Roman,Times,serif,-webkit-standard;"><span style="color: blue;"><span style="font-size: 14px;">&nbsp;</span></span></span></div>
                                    <div style="box-sizing: border-box; margin-bottom: 0.0001pt; text-align: left; line-height: normal; background: white;"><span style="font-family: Times New Roman,Times,serif,-webkit-standard;"><span style="color: blue;"><span style="font-size: 14px;">4. One of the Director must definitely be a resident of India</span></span></span></div>
                                    <div style="box-sizing: border-box; margin-bottom: 0.0001pt; text-align: left; line-height: normal; background: white;"><span style="font-family: Times New Roman,Times,serif,-webkit-standard;"><span style="color: blue;"><span style="font-size: 14px;">&nbsp;</span></span></span></div>
                                    <div style="box-sizing: border-box; margin-bottom: 0.0001pt; text-align: left; line-height: normal; background: white;"><span style="font-family: Times New Roman,Times,serif,-webkit-standard;"><span style="color: blue;"><span style="font-size: 14px;">5. The minimum advisable Authorised Share Capital is INR 1 lakh</span></span></span></div>
                                    <div style="box-sizing: border-box; margin-bottom: 0.0001pt; text-align: left; line-height: normal; background: white;"><span style="font-family: Times New Roman,Times,serif,-webkit-standard;"><span style="color: blue;"><span style="font-size: 14px;">&nbsp;</span></span></span></div>
                                    <div style="box-sizing: border-box; margin-bottom: 0.0001pt; text-align: left; line-height: normal; background: white;"><span style="font-family: Times New Roman,Times,serif,-webkit-standard;"><span style="color: blue;"><span style="font-size: 14px;">6. DIN (Director Identification Number) for all directors is needed</span></span></span></div>
                                    <div style="box-sizing: border-box; margin-bottom: 0.0001pt; text-align: left; line-height: normal; background: white;"><span style="font-family: Times New Roman,Times,serif,-webkit-standard;"><span style="color: blue;"><span style="font-size: 14px;">&nbsp;</span></span></span></div>
                                    <div style="box-sizing: border-box; margin-bottom: 0.0001pt; text-align: left; line-height: normal; background: white;"><span style='font-size: 14px; color: blue; font-family: "Times New Roman", Times, serif, -webkit-standard;'>7. DSC (Digital Signature Certificate) for 2 promoters and 1 witness is required</span></div></div></div>
                            <div style=' border-box;display: flex;flex-flow: column wrap;align-items: center;width: 798px;max-width: 798px;color: rgb(38, 38, 38);font-family: "Open Sans", sans-serif;font-size: 16px;font-style: normal;font-variant-ligatures: normal;font-variant-caps: normal;font-weight: 400;letter-spacing: 1px;orphans: 2;text-align: left;text-indent: 0px;text-transform: none;white-space: normal;widows: 2;word-spacing: 0px;-webkit-text-stroke-width: 0px;background-color: rgb(255, 255, 255);text-decoration-style: initial;text-decoration-color: initial;'>
                                <br>
                            </div>
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- blog section ends here -->
   
   @include('site.includes.footer');